### ISSUE TITLE
gpu_cc_tool.py not working on H100 PCIe

### ISSUE THREAD

**Issue by YurkoWasHere** [NVIDIA/nvtrust#18]
```
$ python3 gpu_cc_tool.py
```
Yields the following error (enabled debugging)

```
NVIDIA GPU Tools version 535.86.06
DEBUG:root:GPU 0000:02:00.0 ? 0x2331 BAR0 0x29042000000 sanity check of bar0 failed
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 127, in find_gpus_sysfs
    dev = Gpu(dev_path=dev_path)
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 2063, in __init__
    raise BrokenGpuError()
ERROR:root:GPU /sys/bus/pci/devices/0000:02:00.0 broken:
ERROR:root:Config space working True
Traceback (most recent call last):
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 127, in find_gpus_sysfs
    dev = Gpu(dev_path=dev_path)
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 2063, in __init__
    raise BrokenGpuError()
__main__.BrokenGpuError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 2499, in <module>
    main()
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 2443, in main
    gpus, other = find_gpus()
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 146, in find_gpus
    return find_gpus_sysfs(bdf)
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 137, in find_gpus_sysfs
    dev = BrokenGpu(dev_path=dev_path)
  File "/shared/final/nvtrust/host_tools/python/gpu_cc_tool.py", line 1269, in __init__
    self.bars_configured = self.sanity_check_cfg_space_bars()
AttributeError: 'BrokenGpu' object has no attribute 'sanity_check_cfg_space_bars'. Did you mean: 'sanity_check_cfg_space'?
```

**Comment by rnertney** [comment]
What is the output of `lspci -vd 10de:`?

**Comment by YurkoWasHere** [comment]
Waiting on response from datacenter, looks like server id currently down :(

Don't know if it helps but here is `lspci -vn` which I ran before it was inaccessible.  Will run `-vd` as soon as i can.

```
02:00.0 0302: 10de:2331 (rev a1)
        Subsystem: 10de:1626
        Flags: fast devsel, IRQ 236, IOMMU group 49
        Memory at 29042000000 (64-bit, prefetchable) [size=16M]
        Memory at 2a000000000 (64-bit, prefetchable) [size=128G]
        Memory at 29000000000 (64-bit, prefetchable) [size=32M]
        Capabilities: [40] Power Management version 3
        Capabilities: [48] MSI: Enable- Count=1/16 Maskable+ 64bit+
        Capabilities: [60] Express Endpoint, MSI 00
        Capabilities: [9c] Vendor Specific Information: Len=14 <?>
        Capabilities: [b0] MSI-X: Enable- Count=9 Masked-
        Capabilities: [100] Secondary PCI Express
        Capabilities: [12c] Latency Tolerance Reporting
        Capabilities: [134] Physical Resizable BAR
        Capabilities: [140] Virtual Resizable BAR
        Capabilities: [14c] Data Link Feature <?>
        Capabilities: [158] Physical Layer 16.0 GT/s <?>
        Capabilities: [188] Extended Capability ID 0x2a
        Capabilities: [1b8] Advanced Error Reporting
        Capabilities: [200] Lane Margining at the Receiver <?>
        Capabilities: [248] Alternative Routing-ID Interpretation (ARI)
        Capabilities: [250] Single Root I/O Virtualization (SR-IOV)
        Capabilities: [2a4] Vendor Specific Information: ID=0001 Rev=1 Len=014 <?>
        Capabilities: [2b8] Power Budgeting <?>
        Capabilities: [2c8] Extended Capability ID 0x2e
```

**Comment by rnertney** [comment]
Looks like you already have the NVIDIA driver installed. On the host, you do not need it installed, the gpu tool is meant to operate without it. Can you remove/purge the driver, reboot the system, and then try again?

**Comment by YurkoWasHere** [comment]
I ran ` /usr/bin/nvidia-uninstall` and verified no modules are running

lspci only shows
```
Kernel modules: nouveau
```

Same issue

```
 python3 gpu_cc_tool.py
NVIDIA GPU Tools version 535.86.06
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 127, in find_gpus_sysfs
    dev = Gpu(dev_path=dev_path)
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 2063, in __init__
    raise BrokenGpuError()
2023-10-20,20:56:11.177 ERROR    GPU /sys/bus/pci/devices/0000:02:00.0 broken:
2023-10-20,20:56:11.178 ERROR    Config space working True
Traceback (most recent call last):
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 127, in find_gpus_sysfs
    dev = Gpu(dev_path=dev_path)
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 2063, in __init__
    raise BrokenGpuError()
__main__.BrokenGpuError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 2499, in <module>
    main()
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 2443, in main
    gpus, other = find_gpus()
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 146, in find_gpus
    return find_gpus_sysfs(bdf)
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 137, in find_gpus_sysfs
    dev = BrokenGpu(dev_path=dev_path)
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 1269, in __init__
    self.bars_configured = self.sanity_check_cfg_space_bars()
AttributeError: 'BrokenGpu' object has no attribute 'sanity_check_cfg_space_bars'. Did you mean: 'sanity_check_cfg_space'?

```

**Comment by YurkoWasHere** [comment]
I was able to put the card in CC mode by changing this line

https://github.com/NVIDIA/nvtrust/blob/main/host_tools/python/gpu_cc_tool.py#L55

to 

```
mmio_access_type = "sysfs"
```

I also noticed that this parameter noted in the comment does not seem to exist

https://github.com/NVIDIA/nvtrust/blob/main/host_tools/python/gpu_cc_tool.py#L54C1-L54C81

**Comment by rnertney** [comment]
We are working to release both forms of sysfs/devmem. We have taken your feedback and will work to integrate it into the next file.

**Comment by CasellaJr** [comment]
@YurkoWasHere what did you do after getting that error?
