### ISSUE TITLE
RIM service has no file NV_GPU_VBIOS_G520_0280_895_96009D0002

### ISSUE THREAD

**Issue by nanometerzhu** [NVIDIA/nvtrust#66]
With `curl -X GET "https://rim.attestation.nvidia.com/v1/rim/ids" -H "accept: application/json"`, the newest version RIM service supports is `NV_GPU_VBIOS_G520_0280_895_9600990008`. However, we have a H200 with newer BIOS version: 96.00.9d.00.02. The RIM file `NV_GPU_VBIOS_G520_0280_895_96009D0002`, requests by verifier.cc_admin, is not existed.

Attached the full message here:

```
The system is running in CC DevTools mode !!
Number of GPUs available : 1
-----------------------------------
Fetching GPU 0 information from GPU driver.
Using the Nonce generated by Local GPU Verifier
VERIFYING GPU : 0
  Driver version fetched : 550.90.07
  VBIOS version fetched : 96.00.9d.00.02
  Validating GPU certificate chains.
    The firmware ID in the device certificate chain is matching with the one in the attestation report.
    GPU attestation report certificate chain validation successful.
      The certificate chain revocation status verification successful.
  Authenticating attestation report
    The nonce in the SPDM GET MEASUREMENT request message is matching with the generated nonce.
    Driver version fetched from the attestation report : 550.90.07
    VBIOS version fetched from the attestation report : 96.00.9d.00.02
    Attestation report signature verification successful.
    Attestation report verification successful.
  Authenticating the RIMs.
    Authenticating Driver RIM
      Fetching the driver RIM from the RIM service.
      RIM Schema validation passed.
      driver RIM certificate chain verification successful.
      The certificate chain revocation status verification successful.
      driver RIM signature verification successful.
      Driver RIM verification successful
    Authenticating VBIOS RIM.
      Fetching the VBIOS RIM from the RIM service.
Exception in thread Thread-21 (function_caller):
Traceback (most recent call last):
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/site-packages/verifier/cc_admin_utils.py", line 342, in fetch_rim_file
    with request.urlopen(BaseSettings.RIM_SERVICE_BASE_URL + file_id) as https_response:
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/site-packages/verifier/utils/__init__.py", line 202, in function_caller
    result = function(*arguments)
  File "/root/miniconda3/envs/nvAttest/lib/python3.10/site-packages/verifier/cc_admin_utils.py", line 349, in fetch_rim_file
    raise RIMFetchError("Could not fetch the rim file : " + file_id)        
verifier.exceptions.RIMFetchError: Could not fetch the rim file : NV_GPU_VBIOS_G520_0280_895_96009D0002
```

Please add this RIM file so we can continue the H200 TEE verification.

**Comment by thisiskarthikj** [comment]
@nanometerzhu  We will take a look and get back to you.

**Comment by nanometerzhu** [comment]
@thisiskarthikj do you have any update for this issue?

**Comment by kckeiks** [comment]
Similar issue, except that the request times out.

```
Fetching the driver RIM from the RIM service.
Could not fetch RIM file from RIM service with id : NV_GPU_DRIVER_GH100_555.42.06
Error occurred while fetching the driver RIM from the RIM service due to The fetch_rim_file call timed out.
GPU Attestation failed.
```

**Comment by tolak** [comment]
> NV_GPU_VBIOS_G520_0280_895_96009D0002

Hey @thisiskarthikj, sir, could you bring any update on this? Our business logic relies on this patch to provide full trust-chain verification to our customers. Please let us know how we can push it forward if anything needs to be done from our side🙏

**Comment by h4x3rotab** [comment]
We also need `96.00.A5.00.03` as it's listed as the latest H200 firmware here: https://docs.nvidia.com/dgx/dgxh100-fw-update-guide/version-24-09-1.html

**Comment by liho00** [comment]
@thisiskarthikj Hi ser any update, H200 is widely used now, can we whitelist the firmware asap?

**Comment by amshinde** [comment]
Thank you for the report                                                                
Confirmed that the RIM service is missing entries for both 96.00.9D.00.02 and 96.00.A5.00.03 for the H200 SKU. These correspond to older firmware bundles that were not published to the RIM service at the time. Will flag this internally.
In the meantime, upgrading to a more recent DGX firmware bundle (Dec 2025, 96.00.DA.00.11) would unblock attestation as that version is available in the RIM service.
