### ISSUE TITLE
LocalGPUTest fails and leaves GPU in an invalid state

### ISSUE THREAD

**Issue by kckeiks** [NVIDIA/nvtrust#87]
## Setup
I followed the [Condential Computing Deployment Guide - (Intel TDX & KVM)](https://docs.nvidia.com/cc-deployment-guide-tdx.pdf).

**nvidia-smi**
Driver Version: 560.35.05  (nvidia-driver-560-open)
**cuda-toolkit**
Version 12.6

## Problem

The script fails and leaves my GPU in an invalid state.

```
cudaGetDeviceCount returned 802
-> system not yet initialized
```

This is the error I get when I run the script.

```
[LocalGPUTest] node name : thisNode1
[['LOCAL_GPU_CLAIMS', <Devices.GPU: 2>, <Environment.LOCAL: 2>, '', '', '']]
[LocalGPUTest] call get_evidence()
Nonce generated: 931d8dd0add203ac3d8b4fbde75e115278eefcdceac5b87671a748f32364dfcb
Number of GPUs available : 1
Fetching GPU 0 information from GPU driver.
Exception in thread Thread-14 (function_caller):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/shared/nvAttest/lib/python3.12/site-packages/verifier/utils/__init__.py", line 206, in function_caller
    result = function(*arguments)
             ^^^^^^^^^^^^^^^^^^^^
  File "/shared/nvAttest/lib/python3.12/site-packages/pynvml.py", line 5097, in nvmlDeviceGetConfComputeGpuAttestationReport
    _nvmlCheckReturn(ret)
  File "/shared/nvAttest/lib/python3.12/site-packages/pynvml.py", line 919, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error
        The call to fetch attestation report timed out.
[LocalGPUTest] call attest() - expecting True
Evidence is empty.. skipping attestation..
[LocalGPUTest] call attest() - result :  False
[LocalGPUTest] token :
[LocalGPUTest] call validate_token() - expecting True
[LocalGPUTest] call validate_token() - result:  False
Token is empty
```

Running `snvidia-smi conf-compute -srs 1` after executing the script, returns `Failed to set Conf. Compute GPUs Ready State: Invalid Argument`.

**Comment by steven-bellock** [comment]
For attestation at least, `560` is not supported for confidential compute, only `550` right now. In addition, `nvidia-persistenced` needs to be run before any SMI commands are executed.

**Comment by kckeiks** [comment]
> For attestation at least, `560` is not supported for confidential compute, only `550` right now. In addition, `nvidia-persistenced` needs to be run before any SMI commands are executed.

Thank you. I installed 550 and now the script works. I believe this driver is not completely compatible with cuda-toolkit 12.5 which is the version that the guide uses. Will confidential compute still work if I switch to 12.4?

**Comment by steven-bellock** [comment]
>Will confidential compute still work if I switch to 12.4?

As a feature, yes, but newer CUDA toolkits and can run on older drivers. See https://docs.nvidia.com/deploy/cuda-compatibility/#id3.

**Comment by kckeiks** [comment]
> > Will confidential compute still work if I switch to 12.4?
> 
> As a feature, yes, 

Thanks, we will try that.

> ...but newer CUDA toolkits can run on older drivers. See https://docs.nvidia.com/deploy/cuda-compatibility/#id3.

Our application uses PTX so we've run into issues as mentioned here https://docs.nvidia.com/deploy/cuda-compatibility/#application-considerations-for-minor-version-compatibility.
